# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "nvidia" ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" =
    #{ device = "/dev/disk/by-uuid/66c6426b-2df8-46ac-aa6a-5229211a7ec4";
    #{ device = "/dev/disk/by-id/ata-SanDisk_SDSSDA240G_161362407262-part1";
    { device = "/dev/disk/by-id/nvme-KINGSTON_SNV3S500G_50026B7687140624-part1";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2aa8a487-cc03-4c60-ac7a-3442ad0ca917";
      fsType = "ext4";
    };

  fileSystems."/mnt" =
    { device = "/dev/disk/by-uuid/febe9e30-ade8-4829-b872-dd5310ce9ea7";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4c806fcb-549a-4b0d-9f8f-e72f16c1bfa3"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.nameservers = [ "1.1.1.1" "8.8.8.8" ];
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
