# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-intel" ];
	boot.extraModulePackages = [ ];

	fileSystems."/" =
	{ device = "/dev/disk/by-uuid/4085c9aa-80a8-4f6f-9143-ae066bdd61b9";
		fsType = "ext4";
	};

	fileSystems."/boot" =
	{ device = "/dev/disk/by-uuid/4FD3-F59B";
		fsType = "vfat";
		options = [ "fmask=0077" "dmask=0077" ];
	};

        hardware.bluetooth.enable = true;
	hardware.rtl-sdr.enable = true;
        hardware.opentabletdriver.enable = true;
        hardware.uinput.enable = true;
	powerManagement = {
		enable = true;
		powertop.enable = true;
	};

	swapDevices =
		[ { device = "/dev/disk/by-uuid/7913d425-be7e-4aad-8456-aa397abc2f1e"; }
		];

# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
# (the default) this is the recommended approach. When using systemd-networkd it's
# still possible to use this option, but it's recommended to use it in conjunction
# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
		networking.useDHCP = lib.mkDefault true;
# networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
# networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

		nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
		hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

		services.xserver.videoDrivers = [ "intel" ];  # modesetting didn't help
#			boot.blacklistedKernelModules = [ "nouveau" "nvidia" ];  # bbswitch
			boot.kernelParams = [ "acpi_rev_override=5" "i915.enable_guc=2" ];  
		hardware.graphics = {
			enable = true;
			extraPackages = with pkgs; [
        intel-compute-runtime-legacy1
				vpl-gpu-rt
        intel-media-driver # LIBVA_DRIVER_NAME=iHD
        intel-vaapi-driver
			#	# intel-media-driver # LIBVA_DRIVER_NAME=iHD
# 					vaapiIntel         # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
			#	# 	vaapiVdpau
			#	# intel-vaapi-driver
			];
		};
	environment.sessionVariables = { LIBVA_DRIVER_NAME = "iHD"; };
}
